### ISSUE TITLE
Repository issue

### ISSUE THREAD

**Issue by jkrawczyk** [sqs/sbt-elasticbeanstalk#6]
Hi, it seems that there are some issues with the specified repository. I was trying to use the plugin in non-play application but sbt can't find the module.
BTW the resolver specified in the guide for non-play app seems to be mistaken with the one for play app.
Regards,
Kuba.

**Comment by darthtrevino** [comment]
+1

**Comment by joescii** [comment]
Quinn, when you get some time, let's work on issue #5.  If we have that completed, then we can publish to the sbt-plugins repo and remove the need for the extra resolver.

**Comment by sqs** [comment]
Sorry for neglecting this. I am no longer at the company named by com.blendlabsinc. I've gotten permission from them to keep using that name for this, but would it be OK for me to just use com.qslack? I'll do that unless it would complicate your build setups.

**Comment by joescii** [comment]
I would recommend changing it to `com.qslack` since you're not at blendlabs any longer.  I have no problems changing my build script to utilize the new name.

**Comment by darthtrevino** [comment]
Either way is fine - it's not really usable for me in its present state

**Comment by joescii** [comment]
Let me know if there is anything I can do to help.  I should have a couple of hours Sunday to work on this.

**Comment by sqs** [comment]
Someone wanna just take over this project and publish it? That would be best. :)

**Comment by joescii** [comment]
Yeah, if you aren't using it anyway.  Just send it my way.  I think you can make me the owner or whatever.

**Comment by joescii** [comment]
I'm actively working on this.  I've changed the organization to my domain (com.joescii), and I'm working to get it published to the sbt community repo which is in the resolvers by default.  Once I get some of the issues straightened out, I'll let everyone know.

**Comment by darthtrevino** [comment]
Awesome! Thanks, Joe!

**Comment by sqs** [comment]
Great, thanks!

**Comment by joescii** [comment]
This is really close to being done.  I'm waiting on Josh Suereth to approve the mirroring of my repo to the sbt community repo.  If you don't want to wait, add my bintray repo (http://dl.bintray.com/barnesjd/sbt-plugins) as a resolver and set the plugin version to `0.0.7`.  Once he does that, there will not be a resolver requirement to use the plugin.  Thanks for the patience, folks!

**Comment by joescii** [comment]
I finally got the bintray repo straightened out, and I have verified that we can pull 0.0.7 from the community plugins.  Sorry for such a long wait.  Now that everything is straightened out with the repo, we should have no problems updating in the future.
